ruby/WataruBook/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get '/users' => 'users#index'
  get '/users/:id' => 'users#show'
  
  resources :articles do
  	resources :comments
  end
  resources :articles do
	resource :like, only: [:create, :destroy]
  end
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

ruby/WataruBook/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

ruby/WataruBook/app/models/article.rb
class Article < ApplicationRecord
	belongs_to :user
	has_many :comments
	mount_uploader :image, ImageUploader
	has_many :likes
	def liked_by? user
		# whereはたくさん持ってこれる
    	likes.where(user_id: user.id).exists?
	end

end

ruby/WataruBook/app/models/comment.rb
class Comment < ApplicationRecord
	belongs_to :article
	belongs_to :user
end

ruby/WataruBook/app/models/like.rb
class Like < ApplicationRecord
	
  	belongs_to :article
    belongs_to :user
end

ruby/WataruBook/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :articles
  has_many :likes
  has_many :comments
  
  
end

ruby/WataruBook/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

ruby/WataruBook/app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /articles
  # GET /articles.json
  def index
    @articles = Article.all
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
    @article = Article.find(params[:id])
    @comment = Comment.new
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles
  # POST /articles.json
  def create
    @article = Article.new(article_params)

    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: 'Article was successfully created.' }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1
  # PATCH/PUT /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to @article, notice: 'Article was successfully updated.' }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article.destroy
    respond_to do |format|
      format.html { redirect_to articles_url, notice: 'Article was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def article_params
      params.require(:article).permit(:title, :body, :author, :user_id, :image)
    end
end

ruby/WataruBook/app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]
  # before_action :authenticate_user!

  # GET /comments
  # GET /comments.json
  def index
    @comments = Comment.all
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
    
  end

  # GET /comments/new
  def new
    @article = Article.find(params[:article_id])
    @comment = @article.comments.build
    # @comment = Comment.new
  end

  # GET /comments/1/edit
  def edit
    @article = @comment.article
  end

  # POST /comments
  # POST /comments.json
  def create
    @article = Article.find(params[:article_id])
    @comment = Comment.new(comment_params)
    @comment.user_id = current_user.id
    redirect_to article_path(@article)

    respond_to do |format|
      if @comment.save
        format.html { redirect_to @article, notice: 'Comment was successfully created.'}
        format.json { render :show, status: :created, location: @article } and return

      else
        format.html { render :new }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to article_comment_path(@comment), notice: 'Comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to comments_url, notice: 'Comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])

    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:content, :article_id)
    end
end

ruby/WataruBook/app/controllers/likes_controller.rb
class LikesController < ApplicationController
	before_action :authenticate_user!
	
    def create
        article = Article.find(params[:article_id])
        current_user.likes.create(article_id: article.id)
        
        
        # like = Like.new
        # like.user_id = current_user.id
        # like.article_id = article.id
        # like.save

		redirect_to articles_path
	end

    def destroy
        article = Article.find(params[:article_id])
        like = current_user.likes.find_by(article_id: article.id)
        like.destroy

		redirect_to articles_path
    end
end

ruby/WataruBook/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
  	@users = User.all
  end
  def show
  	@user = User.find(params[:id])
  	
  end
end

ruby/WataruBook/app/helpers/application_helper.rb
module ApplicationHelper
end

ruby/WataruBook/app/helpers/articles_helper.rb
module ArticlesHelper
end

ruby/WataruBook/app/helpers/comments_helper.rb
module CommentsHelper
end

ruby/WataruBook/app/helpers/likes_helper.rb
module LikesHelper
end

ruby/WataruBook/app/helpers/users_helper.rb
module UsersHelper
end

ruby/WataruBook/app/views/articles/_form.html.erb
<%= form_for(article) do |f| %>
  <% if article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
      <% article.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :body %>
    <%= f.text_area :body %>
  </div>

  <div class="field">
    <%= f.label :author %>
    <%= f.text_field :author %>
  </div>

  <div class="field">
    <%= f.label :user_id %>
    <%= f.collection_select :user_id, User.all, :id, :id %>
  </div>

  <div class="field">
    <%= f.label :image %>
    <%= f.file_field :image %> 
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

ruby/WataruBook/app/views/articles/edit.html.erb
<h1>Editing Article</h1>

<%= render 'form', article: @article %>

<%= link_to 'Show', @article %> |
<%= link_to 'Back', articles_path %>

ruby/WataruBook/app/views/articles/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Articles</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Body</th>
      <th>Author</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @articles.each do |article| %>
      <tr>
        <% if article.image? %>
    　     <td><%=  image_tag article.image.url%></td>
        <% else %>
    　     <td><%= image_tag 'noimage.gif' %></td>
    　  <% end %>
        <td><%= article.title %></td>
        <td><%= article.body %></td>
        <td><%= article.author %></td>
        <td><%= article.user_id %></td>
        <td><%= link_to 'Show', article %></td>
        <td><%= link_to 'Edit', edit_article_path(article) %></td>
        <td><%= link_to 'Destroy', article, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <td>
          <% if article.liked_by? current_user %>
            <%= link_to "いいね解除", article_like_path(article.id), method: :delete %>
          <% else %>
            <%= link_to "いいね", article_like_path(article.id), method: :post %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Article', new_article_path %>

ruby/WataruBook/app/views/articles/new.html.erb
<h1>New Article</h1>

<%= render 'form', article: @article %>

<%= link_to 'Back', articles_path %>

ruby/WataruBook/app/views/articles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @article.title %>
</p>

<p>
  <strong>Body:</strong>
  <%= @article.body %>
</p>

<p>
  <strong>Author:</strong>
  <%= @article.user.email %>
  
</p>

<p>
  <strong>User:</strong>
  <%= @article.user_id %>
</p>
<p>コメントの追加</p>
  <%= form_for([@article, @comment]) do |f| %>
  
  <p>
    <%= f.label :content %><br>
    <%= f.text_area :content %>
  </p>
  <p>
    <%= f.hidden_field :article_id, :value => @article.id %>
  </p>
  
  <p>
    <%= f.submit %>
  </p>
  <% end %>
	<strong>Comment:</strong>
	<% @article.comments.each do |comment| %>
  
<div id="user"> ユーザーID</div>
   <%= comment.user_id %><br>
<div id="comment"> コメント</div>
	 <%= comment.content %>
  
  <% end %>
</p>
<td>
  <% if @article.liked_by? current_user %>
      <%= link_to "いいね解除", article_like_path(@article.id), method: :delete %>
  <% else %>
      <%= link_to "いいね", article_like_path(@article.id), method: :post %>
  <% end %>
</td>
<%= link_to 'Edit', edit_article_path(@article) %> |
<%= link_to 'Back', articles_path %>

ruby/WataruBook/app/views/comments/_form.html.erb
<%= form_for([article, comment]) do |f| %>
  <% if comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :content %>
    <%= f.text_area :content %>
  </div>

  <div class="field">
    <%= f.label :article_id %>
    <%= f.number_field :article_id %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

ruby/WataruBook/app/views/comments/edit.html.erb
<h1>Editing Comment</h1>

<%= render 'form', comment: @comment, article: @article %>

<%= link_to 'Show', article_comment_path(@comment) %> |
<%= link_to 'Back', article_comment_path %>

ruby/WataruBook/app/views/comments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Comments</h1>

<table>
  <thead>
    <tr>
      <th>Content</th>
      <th>Article</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.content %></td>
        <td><%= comment.article_id %></td>
        <td><%= link_to 'Show', comment %></td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_comment_path %>

ruby/WataruBook/app/views/comments/new.html.erb
<h1>New Comment</h1>

<%= render 'form', comment: @comment, article: @article %>

<%= link_to 'Back', comments_path %>

ruby/WataruBook/app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Content:</strong>
  <%= @comment.content %>
</p>

<p>
  <strong>Article:</strong>
  <%= @comment.article_id %>
</p>

<%= link_to 'Edit', edit_article_comment_path(@comment) %> |
<%= link_to 'Back', article_comment_path %>

ruby/WataruBook/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WataruBook</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
   <% if user_signed_in? %>
      Logged in as <%= current_user.email %>
      <%= link_to "ログアウト", destroy_user_session_path, method: :delete %>
    <% else %>
      <%= link_to "サインアップ", new_user_registration_path %> |
      <%= link_to "ログイン", new_user_session_path %>
    <% end %>
    <%= yield %>
  </body>
</html>

ruby/WataruBook/app/views/users/index.html.erb
<h1>Users#index</h1>
<h2>User一覧</h2>
<% @users.each do |user| %>
	<%= user.email %><br>
	
<% end %>
<p>Find me in app/views/users/index.html.erb</p>

ruby/WataruBook/app/views/users/show.html.erb
<h1><%= @user.email %> さんのページだよ</h1>
<% @user.articles.each do |article| %>
	<%= article.title %>
	<%= article.body %>
	<%= article.author %><br>
<% end %>